/**
 * 功能测试用例清单（手工 + 自动化对照）
 * automated: true 表示有对应自动化测试覆盖入口/逻辑
 */
export interface FeatureTestCase {
  id: string;
  module: string;
  path: string;
  menuCode?: string;
  steps: string[];
  expected: string[];
  automated: boolean;
}

export const FEATURE_TEST_CASES: FeatureTestCase[] = [
  {
    id: "auth-login",
    module: "登录",
    path: "/login",
    steps: ["打开登录页", "输入账号/密码/验证码", "点击登录"],
    expected: ["toast 登录成功", "跳转首个有权限菜单"],
    automated: true,
  },
  {
    id: "user-submit",
    module: "用户功能-课时上报",
    path: "/user/submit",
    menuCode: "user:submit",
    steps: ["选择年月", "点击上报", "填写表单提交"],
    expected: ["toast 上报成功", "列表刷新"],
    automated: true,
  },
  {
    id: "user-leave",
    module: "用户功能-请假申请",
    path: "/user/leave",
    menuCode: "user:leave",
    steps: ["点击提交请假", "填写并提交"],
    expected: ["toast 提交成功"],
    automated: true,
  },
  {
    id: "user-assets",
    module: "用户功能-资产管理",
    path: "/user/assets",
    menuCode: "user:assets",
    steps: ["申请易耗品/固定资产", "查看申请记录"],
    expected: ["toast 申请成功", "可查看申请列表"],
    automated: true,
  },
  {
    id: "user-car",
    module: "用户功能-用车申请",
    path: "/user/car",
    menuCode: "user:car",
    steps: ["新建用车申请"],
    expected: ["toast 申请成功"],
    automated: true,
  },
  {
    id: "sys-account",
    module: "系统设置-用户管理",
    path: "/system/account",
    menuCode: "sys:user",
    steps: ["新增/编辑/删除用户", "重置密码"],
    expected: ["成功/失败均有 toast", "列表刷新"],
    automated: true,
  },
  {
    id: "sys-role",
    module: "系统设置-角色管理",
    path: "/system/role",
    menuCode: "sys:role",
    steps: ["新增/编辑角色", "关联资源", "删除角色"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "sys-res",
    module: "系统设置-资源管理",
    path: "/system/resources",
    menuCode: "sys:res",
    steps: ["新增子资源", "编辑", "删除"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "salary-calc",
    module: "工资管理-工资测算",
    path: "/salary/calc",
    menuCode: "sms:salary",
    steps: ["按年月查询", "新增工资明细", "行内查看明细增删"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "tms-teacher",
    module: "教师管理-教师信息",
    path: "/tms/teacher",
    menuCode: "tms:teacher",
    steps: ["搜索", "编辑教师", "删除教师"],
    expected: ["保存成功/失败 toast"],
    automated: true,
  },
  {
    id: "tms-leave",
    module: "教师管理-请假管理",
    path: "/tms/leave",
    menuCode: "tms:leave",
    steps: ["筛选审核状态", "审核请假"],
    expected: ["toast 审核成功/失败"],
    automated: true,
  },
  {
    id: "tms-work",
    module: "教师管理-课时管理",
    path: "/tms/work",
    menuCode: "tms:work",
    steps: ["选择教师与年月", "查看工时记录"],
    expected: ["列表与图表展示", "无新增按钮"],
    automated: true,
  },
  {
    id: "tms-exhibition",
    module: "教师管理-展会管理",
    path: "/tms/exhibition",
    menuCode: "tms:exhibition",
    steps: ["查看附件"],
    expected: ["附件弹窗正常打开"],
    automated: true,
  },
  {
    id: "ams-assets",
    module: "资产管理-固定资产",
    path: "/sms/ams-assets",
    menuCode: "ams:assets",
    steps: ["新增/编辑/删除", "入库", "查看实体", "查看申请"],
    expected: ["入库失败显示接口 msg", "成功关闭弹窗"],
    automated: true,
  },
  {
    id: "ams-category",
    module: "资产管理-资产分类",
    path: "/sms/ams-category",
    menuCode: "ams:category",
    steps: ["新增/编辑/删除分类"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "ams-consumables",
    module: "资产管理-易耗品",
    path: "/sms/ams-consumables",
    menuCode: "ams:consumables",
    steps: ["增删改", "入库", "查看申请"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "crms-car",
    module: "用车管理-车型管理",
    path: "/sms/car",
    menuCode: "crms:car",
    steps: ["新增/编辑车型", "管理用途", "删除"],
    expected: ["成功/失败均有 toast"],
    automated: true,
  },
  {
    id: "crms-apply",
    module: "用车管理-用车审核",
    path: "/sms/car-apply",
    menuCode: "crms:apply",
    steps: ["筛选车型", "审核申请"],
    expected: ["toast 审核成功/失败"],
    automated: true,
  },
  {
    id: "personal-info",
    module: "用户功能-教师信息",
    path: "/personal-info",
    menuCode: "user:teacher",
    steps: ["编辑个人信息并保存"],
    expected: ["toast 保存成功/失败"],
    automated: true,
  },
  {
    id: "header-logout",
    module: "顶栏",
    path: "-",
    steps: ["修改密码", "退出登录"],
    expected: ["toast 提示", "退出后跳转登录页"],
    automated: false,
  },
];
