/** /common/dict 字典编码，与后端保持一致 */
export const DictCode = {
  META_TYPE: "META_TYPE",
  GENDER: "TEACHER_GENDER",
  POLITICAL_STATUS: "TEACHER_POLITICAL_STATUS",
  DEGREE: "TEACHER_DEGREE",
  DEGREE_DURATION: "TEACHER_DEGREE_DURATION",
  FAMILY_RELATION: "TEACHER_FAMILY_RELATION",
  LICENSE_TYPE: "TEACHER_LICENSE_TYPE",
  LEAVE_TYPE: "TEACHER_LEAVE_TYPE",
  WORK_SUBJECT: "TEACHER_WORK_SUBJECT",
  ASSETS_STATUS: "ASSETS_STATUS",
  ASSETS_DISPOSE: "ASSETS_DISPOSE",
  MESSAGE_TARGET: "MESSAGE_TARGET",
  MESSAGE_SSE: "MESSAGE_SSE",
} as const;

export type DictCodeKey = (typeof DictCode)[keyof typeof DictCode];
